from __future__ import annotations

from pathlib import Path
from typing import Any, Iterable

import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine

from config import settings


def _database_url() -> str:
    if settings.database_url:
        # Railway may provide the older postgres:// prefix.
        if settings.database_url.startswith("postgres://"):
            return settings.database_url.replace("postgres://", "postgresql+psycopg://", 1)
        if settings.database_url.startswith("postgresql://"):
            return settings.database_url.replace("postgresql://", "postgresql+psycopg://", 1)
        return settings.database_url

    path = Path(settings.sqlite_path)
    if path.parent != Path("."):
        path.parent.mkdir(parents=True, exist_ok=True)
    return f"sqlite:///{path}"


ENGINE: Engine = create_engine(
    _database_url(),
    pool_pre_ping=True,
    future=True,
)


SCHEMA = [
    """
    CREATE TABLE IF NOT EXISTS settings (
        board VARCHAR(20) PRIMARY KEY,
        enabled INTEGER NOT NULL DEFAULT 1
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS accounts (
        board VARCHAR(20) PRIMARY KEY,
        cash DOUBLE PRECISION NOT NULL,
        starting_cash DOUBLE PRECISION NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS positions (
        board VARCHAR(20) NOT NULL,
        symbol VARCHAR(30) NOT NULL,
        quantity DOUBLE PRECISION NOT NULL,
        average_price DOUBLE PRECISION NOT NULL,
        updated_at VARCHAR(40) NOT NULL,
        PRIMARY KEY (board, symbol)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS trades (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        board VARCHAR(20) NOT NULL,
        symbol VARCHAR(30) NOT NULL,
        side VARCHAR(10) NOT NULL,
        quantity DOUBLE PRECISION NOT NULL,
        price DOUBLE PRECISION NOT NULL,
        value DOUBLE PRECISION NOT NULL,
        reason TEXT,
        timestamp VARCHAR(40) NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS signals (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        board VARCHAR(20) NOT NULL,
        symbol VARCHAR(30) NOT NULL,
        action VARCHAR(10) NOT NULL,
        score DOUBLE PRECISION NOT NULL,
        confidence INTEGER NOT NULL,
        price DOUBLE PRECISION NOT NULL,
        reason TEXT,
        timestamp VARCHAR(40) NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS equity (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        board VARCHAR(20) NOT NULL,
        equity DOUBLE PRECISION NOT NULL,
        cash DOUBLE PRECISION NOT NULL,
        positions_value DOUBLE PRECISION NOT NULL,
        timestamp VARCHAR(40) NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS bot_status (
        board VARCHAR(20) PRIMARY KEY,
        last_run VARCHAR(40),
        last_error TEXT,
        scan_count INTEGER NOT NULL DEFAULT 0
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS forecast_cache (
        symbol VARCHAR(30) NOT NULL,
        horizon_days INTEGER NOT NULL,
        payload TEXT NOT NULL,
        updated_at VARCHAR(40) NOT NULL,
        PRIMARY KEY (symbol, horizon_days)
    )
    """,
]


def init_db() -> None:
    # SQLite does not support the exact PostgreSQL identity syntax.
    schema = SCHEMA
    if ENGINE.url.get_backend_name() == "sqlite":
        schema = [s.replace("INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", "INTEGER PRIMARY KEY AUTOINCREMENT") for s in SCHEMA]

    with ENGINE.begin() as conn:
        for statement in schema:
            conn.execute(text(statement))


def execute(statement: str, params: dict[str, Any] | None = None) -> None:
    with ENGINE.begin() as conn:
        conn.execute(text(statement), params or {})


def fetch_one(statement: str, params: dict[str, Any] | None = None) -> dict[str, Any] | None:
    with ENGINE.connect() as conn:
        row = conn.execute(text(statement), params or {}).mappings().first()
        return dict(row) if row else None


def fetch_all(statement: str, params: dict[str, Any] | None = None) -> list[dict[str, Any]]:
    with ENGINE.connect() as conn:
        return [dict(row) for row in conn.execute(text(statement), params or {}).mappings().all()]


def dataframe(statement: str, params: dict[str, Any] | None = None) -> pd.DataFrame:
    with ENGINE.connect() as conn:
        return pd.read_sql(text(statement), conn, params=params or {})
